### ISSUE TITLE
access is not working for routes

### ISSUE THREAD

**Issue by herorelative** [umijs/umi#8765] opened 2022-07-28 12:03 UTC
### Discussed in https://github.com/umijs/umi/discussions/8763

<div type='discussions-op-text'>

<sup>Originally posted by **herorelative** July 28, 2022</sup>
it is working fine using with useAccess hook but permissions were not applied to routes. why?

"@umijs/preset-react": "^2.1.4",
"umi": "^3.5.24",</div>

**Comment by sorrycc** [comment] 2022-07-29 02:51
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by sorrycc** 2022-07-29 02:51 UTC

**Comment by herorelative** [comment] 2022-07-29 07:07
minimal reproduction

```
"@umijs/preset-react": "^2.1.4",
"umi": "^3.5.24",
```

Added the following code in app.ts to use redux-toolkit and route permission stopped working.

```
const ReduxProvider = (props) => <Provider store={store} {...props} />;

export function rootContainer(container: React.ReactNode, opts) {
  return React.createElement(ReduxProvider, opts, container);
}
```

**Comment by herorelative** [comment] 2022-07-29 13:21
Solved: using the following approach :)

```
const ReduxProvider = (props: any) => <Provider store={store} {...props} />;

const Wrapper = ({ children, routes }) => (
  <ReduxProvider>
    {React.cloneElement(children, {
      ...children.props,
      routes,
    })}
  </ReduxProvider>
);

export function rootContainer(container) {
  return React.createElement(Wrapper, null, container);
}
```
