### ISSUE TITLE
[Bug] After upgrading on Umi 4, layouts/index.js is skipped

### ISSUE THREAD

**Issue by skitsanos** [umijs/umi#8187] opened 2022-06-22 08:09 UTC
## What happens?

Just upgraded umi to v.4.0.0 and my layout is not being picked up anymore. worked just fine in v.3.x

Did something change related to layouts?

## Context

- **Umi Version**: 4.0.0
- **Node Version**: 16.15.0
- **Platform**: OSX

package.json dependencies:
```json
{
"dependencies": {
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-card": "^1.20.10",
    "@ant-design/pro-form": "^1.69.4",
    "@ant-design/pro-layout": "^6.38.9",
    "ahooks": "^3.5.0",
    "antd": "^4.21.3",
    "braft-editor": "^2.3.9",
    "dayjs": "^1.11.3",
    "react": "^18.2.0",
    "react-custom-scrollbars": "^4.2.1",
    "react-dom": "^18.2.0",
    "react-entities": "^1.3.0",
    "umi": "^4.0.0",
    "umi-request": "^1.4.0"
  }
}
```

Folder structure:
```
src/
--layouts/
----index.js
--pages/
----index.js
.umirc.js
package.json
```

**Comment by xierenyuan** [comment] 2022-06-22 09:52
can you provide a reproduction of the demo?

**Comment by sorrycc** [comment] 2022-06-24 07:18
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by sorrycc** 2022-06-24 07:18 UTC

**Comment by skitsanos** [comment] 2022-06-27 11:48
Here it is https://github.com/skitsanos/default-dashboard/tree/umi4

**Comment by xierenyuan** [comment] 2022-06-27 14:29
> > can you provide a reproduction of the demo?
> 
> @xierenyuan you can see it in this branch https://github.com/skitsanos/default-dashboard/tree/umi4 What used to work in Umi3, now, in Umi4 got no layouts...

Hi Currently only .tsx suffix is supported in the convention layout, it has been mentioned pr support can be tried in the next version, or first change layouts/index.js to layouts/index.tsx
