### ISSUE TITLE
error - AssertionError [ERR_ASSERTION]: filePath not found of immer

### ISSUE THREAD

**Issue by teamco** [umijs/umi#8175] opened 2022-06-21 20:54 UTC
Error during application start

**info  - Umi v4.0.0**

ready - App listening at http://127.0.0.1:8003
event - [Webpack] Compiled in 11900 ms (1374 modules)
info  - [MFSU] buildDeps since cacheDependency has changed
wait  - [Webpack] Compiling...
event - [Webpack] Compiled in 1234 ms (947 modules)
wait  - [Webpack] Compiling...
event - [Webpack] Compiled in 584 ms (947 modules)
**error - AssertionError [ERR_ASSERTION]: filePath not found of immer**
    at Dep.buildExposeContent (.../node_modules/.pnpm/@umijs+mfsu@4.0.0/node_modules/@umijs/mfsu/dist/dep/dep.js:54:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DepBuilder.writeMFFiles (.../node_modules/.pnpm/@umijs+mfsu@4.0.0/node_modules/@umijs/mfsu/dist/depBuilder/depBuilder.js:103:29)
    at async DepBuilder.build (.../node_modules/.pnpm/@umijs+mfsu@4.0.0/node_modules/@umijs/mfsu/dist/depBuilder/depBuilder.js:73:13)
    at async MFSU.buildDeps (.../node_modules/.pnpm/@umijs+mfsu@4.0.0/node_modules/@umijs/mfsu/dist/mfsu.js:212:9) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: null,
  expected: true,
  operator: '=='
}

**Comment by sorrycc** [comment] 2022-06-24 07:30
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by sorrycc** 2022-06-24 07:30 UTC

**Comment by dashengqi** [comment] 2022-08-15 00:54
error - AssertionError [ERR_ASSERTION]: filePath not found of E:/web/cloud-open-dev/myapp/node_modules/@umijs/preset-umi/node_modules/@umijs/renderer-react
    at Dep.buildExposeContent (E:\web\cloud-open-dev\node_modules\@umijs\mfsu\dist\dep\dep.js:87:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DepBuilder.writeMFFiles (E:\web\cloud-open-dev\node_modules\@umijs\mfsu\dist\depBuilder\depBuilder.js:133:23)
    at async DepBuilder.build (E:\web\cloud-open-dev\node_modules\@umijs\mfsu\dist\depBuilder\depBuilder.js:108:7)
    at async MFSU.buildDeps (E:\web\cloud-open-dev\node_modules\@umijs\mfsu\dist\mfsu\mfsu.js:211:5) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: null,
  expected: true,
  operator: '=='
}

**Comment by dashengqi** [comment] 2022-08-15 01:00
at Dep.buildExposeContent (E:\web\cloud-open-dev\node_modules@umijs\mfsu\dist\dep\dep.js:87:31)
请问这个node_modules下的dep.js文件会引用（E:/web/cloud-open-dev/myapp/node_modules/@umijs/preset-umi/node_modules/@umijs/renderer-react）的绝对地址吗？
/myapp/node_modules/这个目录有变更，所以到值dep.js无法引用到@umijs/renderer-react这个包，导致报错。
删除node_modules重新安装以后就可以了啊
