### ISSUE TITLE
[Bug] Cannot use umi imports with tests

### ISSUE THREAD

**Issue by jaegerbombb** [umijs/umi#7127] opened 2021-08-05 11:50 UTC
## What happens?

Using Jest and Enzyme (also tried react testing library) I cannot mount a component without errors. `umi` imports are undefined or not found.

One solution is to remove `umi` imports and use the native packages but our codebase is already becoming large and using `umi` imports everywhere so we do not want to change them all manually to solve this.

Similar issue has been reported before https://github.com/umijs/umi/issues/4358

## How To Reproduce

Write a test for a component that uses an `umi` import.

e.g. `import { FormattedMessage } from 'umi'`

## Context

- **Umi Version**: 3.4.23
- **Node Version**: 14.16.0
- **Platform**: OSX

**Comment by PeachScript** [comment] 2021-09-06 06:26
We can import from the temp dir, such as `import { FormattedMessage } from '../.umi-test/plugin-locale/localeExports'`

refer: https://umijs.org/plugins/best-practice#%E4%B8%B4%E6%97%B6%E6%96%87%E4%BB%B6%E6%B5%8B%E8%AF%95

**Comment by PeachScript** [comment] 2021-09-06 06:27
Duplicate of #4358

**Closed by PeachScript** 2021-09-06 06:27 UTC
